# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PNPM_STORE_DIR: node_modules/.pnpm-store
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: always-upload-cache
      uses: pat-s/always-upload-cache@v2.1.3
      with:
        path: ${{ env.PNPM_STORE_DIR }}
        key:  -dependency-
    - name: Install dependency
      run: |
        npm config set store-dir ${{ env.PNPM_STORE_DIR }}
        npm install -g pnpm
        pnpm install
    - name: Generate static site
      run: pnpm run export
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./__sapper__/export
